spring.application.name=sst-admin-management

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=examin
spring.datasource.password=examin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Additional optional configurations
spring.jpa.properties.hibernate.format_sql=true
